/**
 * What the two emails say.
 *
 * Kept apart from `transport.js` so the wording can be read and changed without
 * reading the SMTP mechanics, and so every message this app sends is visible in
 * one file. Plain text only — see the note in `transport.js`.
 *
 * Both templates name the app and state how long the thing they carry is good
 * for, because both arrive unprompted from the recipient's point of view: one
 * lands seconds after a sign-up they may have abandoned, the other after an
 * admin action they did not ask for and cannot see.
 */

const APP_NAME = "eFootball Ban & Pick";

/** The confirmation link. `hours` is stated rather than assumed — the expiry
    lives in `verification.js` and the two must not drift into disagreement. */
export function verificationEmail({ username, url, hours }) {
  return {
    subject: `Confirm your email — ${APP_NAME}`,
    text: [
      `Hi ${username},`,
      "",
      `An account was created for you on ${APP_NAME}. Confirm this address to`,
      "finish signing up — you cannot sign in until you do.",
      "",
      url,
      "",
      `The link works once and expires in ${hours} hours.`,
      "",
      "If this was not you, ignore this message: the account stays unusable",
      "until somebody clicks that link.",
    ].join("\n"),
  };
}

/** The password a master admin generated. There is no link here on purpose —
    an emailed sign-in link would be a second way into an account, and this app
    has one. */
export function newPasswordEmail({ username, password, signInUrl }) {
  return {
    subject: `Your new password — ${APP_NAME}`,
    text: [
      `Hi ${username},`,
      "",
      `An administrator reset your ${APP_NAME} password. The new one is:`,
      "",
      `    ${password}`,
      "",
      `Sign in at ${signInUrl} and change it under Edit Profile — this password`,
      "was generated by the server and has been sent through email, so treat it",
      "as temporary.",
      "",
      "If you did not expect this, tell whoever runs the site: somebody with",
      "console access changed your password.",
    ].join("\n"),
  };
}
